mod pow;
mod rsa;

use pow::find_hash_with_prefix;
use rsa::{generate_rsa_keypair, sign_data, verify_signature};

fn main() {
    let nickname = "Eric";
    println!("============== PoW + RSA Implementation ==============");
    println!("Nickname: {}", nickname);

    // Step 1: Generate RSA public/private keypair
    println!("\n=== Step 1: Generate RSA public/private keypair ===");
    let (private_key, public_key) = generate_rsa_keypair();
    println!("Private key generated successfully");
    println!("Public key generated successfully");
    println!("Key length: 2048 bits");

    // Step 2: Perform POW calculation
    println!("\n=== Step 2: Perform POW calculation ===");
    let pow_result = find_hash_with_prefix(nickname, 4)
        .expect("PoW hash not found");

    // Step 3: Sign data using the private key
    println!("\n=== Step 3: Sign data using the private key ===");
    let signature = sign_data(&private_key, &pow_result.input);
    println!("Signature successful!");
    println!("Signature length: {} bits", signature.len());

    // Step 4: Verify signature using public key
    println!("\n=== Step 4: Verify signature using public key ===");
    let is_valid = verify_signature(&public_key, &pow_result.input, &signature);

    if is_valid {
        println!("✔ Signature verification successful");
        println!("✔ The POW result is indeed generated by the corresponding private key holder.");
    } else {
        println!("✘ Signature verification failed");
    }

    // Step 5: Verification failure after demonstration of failed data tampering
    println!("\n=== Step 5: Verification failure after demonstration of failed data tampering ===");
    let tampered_data = format!("{}{}", nickname, pow_result.nonce + 1);
    let is_valid_tampered = verify_signature(&public_key, &tampered_data, &signature);

    if !is_valid_tampered {
        println!("✔ Verification failed after data tampering (as expected).");
    }
}   